### PR TITLE
Commented duplicate return statement

### PR DESCRIPTION
**Pull request by schillingjerrid**
Two return statements, one didn't have semicolon and it was commented.

### CODE REVIEW

**Comment by schillingjerrid** [comment]
@mariomarine Not sure if this was causing any issues but noticed a duplicate return statement without a semicolon

**Comment by rbuchmeier** [comment]
I agree, that was probably accidentally left after doing some debugging.
@StrangeNectar looks like you made the last commit here. But it looks like you may have copied the code from somewhere else. Just for practice, it is worth having your review since you made the last change to it.
@schillingjerrid once ben responds (or in a couple days if he doesn't), feel free to merge it in. Also setting us as reviewers can be helpful.

**Review by rbuchmeier — COMMENTED** [review]
@schillingjerrid I would probably remove the line rather than just comment it out.

**Comment by schillingjerrid** [comment]
@mariomarine No problem. I had just commented it out because the code below was commented as well. I agree it seems like it was part of the original code and then missed when a section was commented out. I'll update the PR.

**Review by bluegroneman — APPROVED** [review]

**Pull request merged**
